apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlb-ninja-app
  namespace: team-ninja-nlb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: 971863113778.dkr.ecr.us-east-1.amazonaws.com/ninjaapp:v1.0.0
          ports:
            - name: tcp
              containerPort: 80