apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlb-ninja-app
  namespace: team-ninja-nlb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: public.ecr.aws/nginx/nginx:1.21
          ports:
            - name: tcp
              containerPort: 80