apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-2048
  namespace: team-2048
spec:
  replicas: 3
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ninja
  template:
    metadata:
      labels:
        app: ninja
    spec:
      containers:
      - name: ninja
        image: 971863113778.dkr.ecr.us-east-1.amazonaws.com/ninjaapp:v1.1.0
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
            requests:
                memory: "64Mi"
                cpu: "250m"
            limits:
                memory: "128Mi"
                cpu: "500m"
      {{ if .Values.spec.karpenterInstanceProfile }}
      nodeSelector: # <- add nodeselector, toleration and spread constraitns
        team: default
        type: karpenter
      tolerations:
        - key: 'karpenter'
          operator: 'Exists'
          effect: 'NoSchedule'
      {{ end }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: ninja
      tolerations:
        - key: 'karpenter'
          operator: 'Exists'
          effect: 'NoSchedule'                
  strategy:
    blueGreen:
      autoPromotionEnabled: false
      activeService: service-2048
      previewService: service-2048-preview
---
apiVersion: v1
kind: Service
metadata:
  namespace: team-2048
  name: service-2048-preview
  labels:
    app: ninja
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    name: app-2048
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: team-2048
  name: ingress-2048-preview
  labels:
    app: ninja
  annotations:
{{ if eq .Values.spec.ingress.type "nginx" }}
    kubernetes.io/ingress.class: "nginx"
{{ else }}
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  {{ if .Values.spec.ingress.host }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
  {{ else }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
  {{ end }}
    alb.ingress.kubernetes.io/tags: Environment={{ .Values.labels.env }},Team=2048
{{ end }}
  {{ if .Values.spec.ingress.host }}
    external-dns.alpha.kubernetes.io/set-identifier: {{ .Values.spec.clusterName }}
    external-dns.alpha.kubernetes.io/aws-weight: '{{ .Values.spec.ingress.route53_weight }}'
    external-dns.alpha.kubernetes.io/ttl: "10"
  {{ end }}     
spec:
{{ if eq .Values.spec.ingress.type "nginx" }}
  kubernetes.io/ingress.class: "nginx"
{{ else }}
  ingressClassName: alb
{{ end }}
  rules:
{{ if .Values.spec.ingress.host }}
    - host: 2048.{{ .Values.spec.ingress.host }}
{{ else }}
    - host: 
{{ end }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-2048-preview
              port:
                number: 80