apiVersion: v1
kind: Service
metadata:
  namespace: team-2048
  name: service-2048
  labels:
    app: ninja
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    name: app-2048